In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"C:\Users\Shruti\Downloads\archive\zomato_dataset.csv")
df.head()

,Restaurant Name,Rating,Cuisine,Average Price,Average Delivery Time,Safety Measure,Location
0,Campus Bakers,4.3,"Bakery, Fast Food, Pizza, Sandwich, Burger",₹50 for one,36 min,Restaurant partner follows WHO protocol,Agra
1,Mama Chicken Mama Franky House,4,"North Indian, Mughlai, Rolls, Burger, Momos",₹50 for one,22 min,Follows all Max Safety measures to ensure your...,Agra
2,GMB - Gopika Sweets & Restaurant,4.2,"North Indian, South Indian, Chinese, Fast Food...",₹50 for one,27 min,Follows all Max Safety measures to ensure your...,Agra
3,Shree Bankey Bihari Misthan Bhandar,4.2,"Mithai, Street Food, South Indian, Chinese, Ic...",₹50 for one,28 min,Restaurant partner follows WHO protocol,Agra
4,Burger King,4.2,"Burger, Fast Food, Beverages",₹50 for one,26 min,Follows all Max Safety measures to ensure your...,Agra

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44891 entries, 0 to 44890
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Restaurant Name        44891 non-null  object
 1   Rating                 44891 non-null  object
 2   Cuisine                44872 non-null  object
 3   Average Price          44891 non-null  object
 4   Average Delivery Time  44891 non-null  object
 5   Safety Measure         44891 non-null  object
 6   Location               44891 non-null  object
dtypes: object(7)
memory usage: 2.4+ MB

In [6]:
#Cleaning Rating: Text - Float
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce')

In [7]:
#Cleaning Average Delivery Time 
df['Average Delivery Time'] = df['Average Delivery Time'].str.replace(' min', '')
df['Average Delivery Time'] = pd.to_numeric(df['Average Delivery Time'], errors='coerce')

In [8]:
#Cleaning Average Price
df['Average Price'] = df['Average Price'].str.replace('₹', '')
df['Average Price'] = df['Average Price'].str.replace(' for one', '')
df['Average Price'] = pd.to_numeric(df['Average Price'], errors='coerce')

In [9]:
df.isnull().sum()

Restaurant Name             0
Rating                   7065
Cuisine                    19
Average Price              58
Average Delivery Time    5299
Safety Measure              0
Location                    0
dtype: int64

In [10]:
df = df.dropna()

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34831 entries, 0 to 44814
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Restaurant Name        34831 non-null  object
 1   Rating                 34831 non-null  float64
 2   Cuisine                34831 non-null  object
 3   Average Price          34831 non-null  float64
 4   Average Delivery Time  34831 non-null  float64
 5   Safety Measure         34831 non-null  object
 6   Location               34831 non-null  object
dtypes: float64(3), object(4)
memory usage: 2.1+ MB

In [12]:
#Top locations
df['Location'].value_counts().head(10)

Location
Kolkata       1258
NCR           1055
Lucknow        979
Hyderabad      900
Kanpur         836
Chandigarh     818
Chennai        798
Indore         795
Mumbai         789
Jaipur         777
Name: count, dtype: int64

In [13]:
#Top Cuisines, Fix: Comma - separated
cuisines = df['Cuisine'].str.split(', ')
cuisine_list = cuisines.explode()

cuisine_list.value_counts().head(10)

Cuisine
North Indian    14560
Fast Food       12781
Chinese         12297
Beverages       10934
Desserts         8144
Street Food      6030
Biryani          6015
Pizza            5320
South Indian     4570
Shake            4099
Name: count, dtype: int64

In [14]:
#Average Rating
df['Rating'].mean()

np.float64(3.9219373546553356)

In [15]:
#Average Delivery Time
df['Average Delivery Time'].mean()

np.float64(33.51692457867991)

In [16]:
#Average Price 
df['Average Price'].mean()

np.float64(174.77132439493553)

In [17]:
#Rating vs Delivery Time 
df.groupby('Rating')['Average Delivery Time'].mean().sort_index()

Rating
2.4    47.000000
2.5    33.687500
2.6    33.129032
2.7    34.000000
2.8    35.321429
2.9    34.536424
3.0    34.712551
3.1    35.225420
3.2    35.634223
3.3    35.049217
3.4    34.788428
3.5    34.747059
3.6    34.546859
3.7    34.145668
3.8    34.173834
3.9    33.890186
4.0    33.723347
4.1    33.233873
4.2    32.908903
4.3    32.480504
4.4    30.826545
4.5    29.015152
4.6    29.959641
4.7    26.363636
4.8    26.142857
4.9    23.250000
Name: Average Delivery Time, dtype: float64

In [18]:
#Cost vs Rating
df.groupby('Rating')['Average Price'].mean().sort_index()

Rating
2.4    200.000000
2.5    187.500000
2.6    193.548387
2.7    212.500000
2.8    175.000000
2.9    182.119205
3.0    176.882591
3.1    176.498801
3.2    178.021978
3.3    174.250559
3.4    178.013817
3.5    168.385621
3.6    174.322034
3.7    173.369611
3.8    175.743440
3.9    173.193436
4.0    175.984191
4.1    173.654800
4.2    176.293996
4.3    177.479275
4.4    170.063202
4.5    172.015152
4.6    166.771300
4.7    176.136364
4.8    250.000000
4.9    112.500000
Name: Average Price, dtype: float64

In [19]:
#Top Restaurants
df.sort_values(by='Rating', ascending=False).head(10)

,Restaurant Name,Rating,Cuisine,Average Price,Average Delivery Time,Safety Measure,Location
32964,Rasoi Ghar Se,4.9,"North Indian, Mithai, Chinese, Street Food",100.0,32.0,Restaurant partner follows WHO protocol,Palakkad
11965,Rambhai Special Butter Patties,4.9,"Street Food, Beverages",100.0,29.0,Restaurant partner follows WHO protocol,Firozabad
40328,Cake Waves,4.9,"Bakery, Fast Food, Desserts",150.0,24.0,Follows all Max Safety measures to ensure your...,Trichy
27235,Hangyo Ice Cream,4.9,"Ice Cream, Desserts",100.0,8.0,Follows all Max Safety measures to ensure your...,Manipal
5046,Ibaco,4.8,Ice Cream,200.0,21.0,Restaurant partner follows WHO protocol,Belgaum
1863,Herbi Vore,4.8,"Fast Food, North Indian",200.0,36.0,Restaurant partner follows WHO protocol,Aligarh
39756,Peni Ice Cream,4.8,Ice Cream,300.0,14.0,Follows all Max Safety measures to ensure your...,Thrissur
27196,Natural Ice Cream,4.8,"Ice Cream, Desserts",200.0,11.0,Restaurant partner follows WHO protocol,Manipal
12154,Sree Ramtilkut Bhandar (Since 1911),4.8,Desserts,200.0,24.0,Follows all Max Safety measures to ensure your...,Gaya
42667,Oasis Vegan Treats,4.8,"Healthy Food, Salad",250.0,43.0,Follows all Max Safety measures to ensure your...,Vadodara

In [21]:
#Price Groups
df['Price Category'] = pd.cut(df['Average Price'],
                             bins=[0, 150, 300, 500, 1000],
                             labels=['Low', 'Medium', 'High', 'Premium'])

In [22]:
df.groupby('Price Category')['Rating'].mean()

C:\Users\Shruti\AppData\Local\Temp\ipykernel_7664\3810931494.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Price Category')['Rating'].mean()

Price Category
Low        3.922578
Medium     3.922959
High       3.908460
Premium    3.935294
Name: Rating, dtype: float64

In [23]:
#Delivery vs Rating
df.groupby(pd.cut(df['Average Delivery Time'], bins=[0, 20, 30, 40, 60]))['Rating'].mean()

C:\Users\Shruti\AppData\Local\Temp\ipykernel_7664\256672225.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(pd.cut(df['Average Delivery Time'], bins=[0, 20, 30, 40, 60]))['Rating'].mean()

Average Delivery Time
(0, 20]     4.041802
(20, 30]    3.939056
(30, 40]    3.900786
(40, 60]    3.887552
Name: Rating, dtype: float64

In [24]:
#Top cuisines by rating
cuisine_df = df.copy()
cuisine_df['Cuisine'] = cuisine_df['Cuisine'].str.split(', ')
cuisine_df = cuisine_df.explode('Cuisine')

cuisine_df.groupby('Cuisine')['Rating'].mean().sort_values(ascending=False).head(5)

Cuisine
Moroccan      4.50
Beverages,    4.45
              4.40
German        4.40
Russian       4.30
Name: Rating, dtype: float64

In [25]:
#Filtering Cuisines with enough Data
cuisine_counts = cuisine_df['Cuisine'].value_counts()

valid_cuisines = cuisine_counts[cuisine_counts > 50].index

filtered = cuisine_df[cuisine_df['Cuisine'].isin(valid_cuisines)]

filtered.groupby('Cuisine')['Rating'].mean().sort_values(ascending=False).head(5)

Cuisine
Paan        4.255556
Japanese    4.141905
Sushi       4.135052
Pancake     4.114667
Mithai      4.087369
Name: Rating, dtype: float64

In [26]:
cuisine_counts.sort_values(ascending=False).head(10)

Cuisine
North Indian    14560
Fast Food       12781
Chinese         12297
Beverages       10934
Desserts         8144
Street Food      6030
Biryani          6015
Pizza            5320
South Indian     4570
Shake            4099
Name: count, dtype: int64

In [27]:
valid_cuisines = cuisine_counts[cuisine_counts > 500].index

In [28]:
filtered = cuisine_df[cuisine_df['Cuisine'].isin(valid_cuisines)]

filtered.groupby('Cuisine')['Rating'].mean().sort_values(ascending=False).head(5)

Cuisine
Mithai          4.087369
Ice Cream       4.086088
Healthy Food    4.039242
Asian           4.038867
Continental     4.003846
Name: Rating, dtype: float64

In [29]:
df.to_csv("cleaned_zomato.csv", index=False)

In [30]:
df.to_csv(r"C:\Users\Shruti\Downloads\cleaned_zomato.csv", index=False)